[app]
name = "wsai"
host = "0.0.0.0"
port = 9091
env = "dev"
enable_register = true

[jwt]
access_ttl = "30m"
refresh_ttl = "720h"
issuer = "ws"
subject = "wsai"

[mysql]
host = "127.0.0.1"
port = 3307
user = "root"
databaseName = "wsai"
charset = "utf8mb4"
maxIdleConns = 10
maxOpenConns = 100

[redis]
host = "127.0.0.1"
port = 6379
db = 0

[rabbitmq]
host = "127.0.0.1"
port = 5672
username = "root"
vhost = "/"

[email]
host = "smtp.qq.com"
port = 465
is_ssl = true

[rag]
qdrant_url = "http://127.0.0.1:6333"
collection = "wsai_doc_chunks"
embedding_model = "embedding-3"
embedding_size = 1024
top_k = 5
