// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/AI/chatMessage/sessions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回当前登录用户创建的所有聊天会话（通常按创建时间降序）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话管理"
                ],
                "summary": "获取当前用户的所有会话列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/backend_internal_handler_session.GetUserSessionsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/AI/chatMessage/sessions/stream": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建一个新会话，同时把用户的第一个问题发给 AI，使用 SSE 流式返回",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "会话管理"
                ],
                "summary": "创建新会话 + 发送第一个问题（SSE 流式返回）",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend_internal_handler_session.CreateSessionAndSendFirstMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE error 事件",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/AI/chatMessage/sessions/{session_id}/messages": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回指定会话 ID 下的所有消息记录（按时间升序）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话管理"
                ],
                "summary": "获取指定会话的全部历史消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/backend_internal_handler_session.GetMeaasgeHistoryResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/AI/chatMessage/sessions/{session_id}/messages/stream": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "向指定的会话 ID 发送一条新消息，并使用 SSE 流式返回 AI 回答",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "会话管理"
                ],
                "summary": "向已有会话追加消息（SSE 流式返回）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "请求参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend_internal_handler_session.SendMessageStreamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE error 事件",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/image/recognize": {
            "post": {
                "description": "上传单张图片，服务端返回识别出的主要类别名称。\n成功时返回 class_name，失败时通过 status_code 和 status_msg 返回错误信息。",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图像识别"
                ],
                "summary": "上传图片进行分类/识别",
                "parameters": [
                    {
                        "type": "file",
                        "description": "要识别的图片文件",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "业务错误时也统一返回 200，通过 status_code 区分",
                        "schema": {
                            "$ref": "#/definitions/backend_internal_handler_image.RecognizeImageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user/captcha": {
            "post": {
                "description": "向指定邮箱发送注册验证码。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "发送邮箱验证码",
                "parameters": [
                    {
                        "description": "邮箱参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend_internal_handler_user.CaptchaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "验证码发送成功",
                        "schema": {
                            "$ref": "#/definitions/backend_internal_handler_user.CaptchaResponse"
                        }
                    },
                    "400": {
                        "description": "邮箱格式错误",
                        "schema": {
                            "$ref": "#/definitions/wsai_backend_internal_common.Response"
                        }
                    },
                    "429": {
                        "description": "发送过于频繁",
                        "schema": {
                            "$ref": "#/definitions/wsai_backend_internal_common.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/login": {
            "post": {
                "description": "根据用户名和密码登录，登录成功后返回 JWT Token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend_internal_handler_user.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功，返回 Token",
                        "schema": {
                            "$ref": "#/definitions/backend_internal_handler_user.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/wsai_backend_internal_common.Response"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/wsai_backend_internal_common.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "将当前请求携带的 JWT Token 加入 Redis 黑名单，后续该 Token 将无法再访问受保护接口。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "用户退出登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token，例如：Bearer eyJhbGciOi...",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "退出登录成功",
                        "schema": {
                            "$ref": "#/definitions/backend_internal_handler_user.LogoutResponse"
                        }
                    },
                    "401": {
                        "description": "未携带有效 Token",
                        "schema": {
                            "$ref": "#/definitions/wsai_backend_internal_common.Response"
                        }
                    },
                    "500": {
                        "description": "服务繁忙或 Redis 不可用",
                        "schema": {
                            "$ref": "#/definitions/wsai_backend_internal_common.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/user/users": {
            "post": {
                "description": "通过邮箱、密码和验证码注册新用户，成功后直接返回 JWT Token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/backend_internal_handler_user.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功，返回 Token",
                        "schema": {
                            "$ref": "#/definitions/backend_internal_handler_user.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误或验证码错误",
                        "schema": {
                            "$ref": "#/definitions/wsai_backend_internal_common.Response"
                        }
                    },
                    "409": {
                        "description": "用户已存在",
                        "schema": {
                            "$ref": "#/definitions/wsai_backend_internal_common.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "backend_internal_handler_image.RecognizeImageResponse": {
            "type": "object",
            "properties": {
                "class_name": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "backend_internal_handler_session.CreateSessionAndSendFirstMessageRequest": {
            "type": "object",
            "required": [
                "modelType",
                "question"
            ],
            "properties": {
                "modelType": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                }
            }
        },
        "backend_internal_handler_session.GetMeaasgeHistoryResponse": {
            "type": "object",
            "properties": {
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/wsai_backend_internal_model.History"
                    }
                },
                "status_code": {
                    "type": "integer"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "backend_internal_handler_session.GetUserSessionsResponse": {
            "type": "object",
            "properties": {
                "sessions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/wsai_backend_internal_model.SessionInfo"
                    }
                },
                "status_code": {
                    "type": "integer"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "backend_internal_handler_session.SendMessageStreamRequest": {
            "type": "object",
            "required": [
                "modelType",
                "question",
                "sessionId"
            ],
            "properties": {
                "modelType": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                },
                "sessionId": {
                    "type": "string"
                }
            }
        },
        "backend_internal_handler_user.CaptchaRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "backend_internal_handler_user.CaptchaResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "type": "integer"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "backend_internal_handler_user.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "backend_internal_handler_user.LoginResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "type": "integer"
                },
                "status_msg": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "backend_internal_handler_user.LogoutResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "type": "integer"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "backend_internal_handler_user.RegisterRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "captcha": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "backend_internal_handler_user.RegisterResponse": {
            "type": "object",
            "properties": {
                "status_code": {
                    "type": "integer"
                },
                "status_msg": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "wsai_backend_internal_common.Response": {
            "type": "object",
            "properties": {
                "status_code": {
                    "type": "integer"
                },
                "status_msg": {
                    "type": "string"
                }
            }
        },
        "wsai_backend_internal_model.History": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "is_user": {
                    "type": "boolean"
                }
            }
        },
        "wsai_backend_internal_model.SessionInfo": {
            "type": "object",
            "properties": {
                "sessionId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "在请求头中填写 Bearer Token，例如：Bearer eyJhbGciOi...",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9091",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "WsAI 后端接口文档",
	Description:      "WsAI 项目的后端接口 Swagger 文档。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
